### ISSUE TITLE
FEATURE: Configure predefined colors

### ISSUE THREAD

**Issue by pmaas** [Sebobo/Shel.Neos.ColorPicker#2]
It would be nice if it would be possible to define the predefined colors below the color picker.

<img width="283" alt="Bildschirmfoto 2019-05-15 um 22 46 54" src="https://user-images.githubusercontent.com/2778669/57808304-5bf8a400-7763-11e9-8e10-0b12e1474ec8.png">

**Comment by Sebobo** [comment]
Great idea, do you want to take a shot at implementing it?

**Comment by pmaas** [comment]
Yes. I try to reserve some time for it next month.

**Comment by Sebobo** [comment]
Sorry, had to to some other change and then it was easy just to add this feature at the same time :)
