### ISSUE TITLE
Option to show Colorpicker without saturation/hue/alpha

### ISSUE THREAD

**Issue by paavo** [Sebobo/Shel.Neos.ColorPicker#46]
I'd love to just show a basic Colorpicker without the additional saturation/hue/alpha settings. 
The option `picker: false` also disable the colorpicker.

**Comment by paavo** [comment]
> Which color mode do you use in this case? `hex`?
yes, `hex`

have a good start into the week

**Comment by Sebobo** [comment]
Then this is resolved via #65 :)
