### ISSUE TITLE
Option to reset presetColors

### ISSUE THREAD

**Issue by paavo** [Sebobo/Shel.Neos.ColorPicker#53]
If i only have 5 "Preset Colors" for example i didn't found a way to disable all the others in the presetColors Array.

**Comment by Sebobo** [comment]
But you can simply override the setting like in your PR?
Why should this be changed in general?

**Comment by paavo** [comment]
Because if `presetColors` is an array with 15 Elements i haven't found a way to disable the preset and only use 3 Elements @Sebobo

**Comment by Sebobo** [comment]
If you override the array and just specify 3 elements, then you should only have those 3? Or am I misunderstanding the issue?

**Comment by paavo** [comment]
> If you override the array and just specify 3 elements, then you should only have those 3?

Tried this some weeks ago, but when i tried to override the array with 3 elements only the first 3 elements were overwritten and the other 15-3 elements in the array were still "there".

**Comment by Sebobo** [comment]
Ah I see. Then we have to make it empty by default...
