### ISSUE TITLE
[BUG] cant set transparency for a color

### ISSUE THREAD

**Issue by mbiberger** [Sebobo/Shel.Neos.ColorPicker#56]
### Description

In v1.4.0 i get a console error if  i set a transparency for a color.

### Steps to Reproduce

1. Go to Inspector
2. Try to change the transparency slider 

#### Expected behavior

I can set transparency for a color. ;-)

#### Actual behavior

Noting happens
Console logs following Error: `Uncaught TypeError: Cannot read properties of undefined (reading 'clientWidth')`

### Affected Versions

Neos: 
7.0.2 // 7.3.0

Shel.Neos.ColorPicker:
1.4.0

**Comment by Sebobo** [comment]
Thx, can reproduce and will check what's going there.

**Comment by Sebobo** [comment]
Should be resolved now with 1.4.1

**Comment by mbiberger** [comment]
Kudos! Thanks Sebastian for the quick processing.
